VERSION: "1.0"
DATABASE: {{ database }}
DBSERVER: {{ dbserver }}
USER: "dbxdba"
DEBUG:
    DISABLE_LOAD: false
    DISABLE_STAGE: false
LOAD:
    COLUMNS: {{ columns }}
    DELIMITER_AS: {{ delimiter }}
    EOL_AS: null
    ERROR_DATA: null
    ERROR_LIMIT: null
    ERROR_LOG: {{ error_log }}
    ESCAPE_AS: {{ escape }}
    FIXED_FORMAT: null
    FIXED_ROW_LENGTH: null
    FORCE_NOT_NULL_COLUMNS: null
    HEADER: null
    IGNORE_EXTRA: null
    IGNORE_LEADING_SPACES: null
    IGNORE_TRAILING: null
    IGNORE_TRAILING_SPACES: null
    INSTEAD_NULL: null
    MODE: {{ fmode }}
    NULL_AS: null
    ON_ERROR: null
    QUOTE_AS: {{ quote }}
    TABLE: {{ table }}
OUTPUT:
    JSON: false
    LOG_BACKUP_COUNT: 2
    LOG_FILE: {{ log_file }}
    LOG_SIZE_MB: 100
SOURCE:
    CRED1: {{ cred1 }}
    CRED2: {{ cred2 }}
    CRED3: {{ cred3 }}
    FILE_SPEC: {{ import_path }}
    FORMAT: {{ fformat }}
    MANIFEST: null
    MULTI_PART: false
    PROTOCOL: "AWS.S3"
    RETRIES: 1
    SPEED_LIMIT_MBS: null
    SPEED_TIME: null
    STREAM_COUNT: 1
    TIMEOUT: 1000
WORK:
    CLEAN_AFTER: true
    CLEAN_BEFORE: true
    JOB_DIR: {{ job_dir }}
    KEEP_FILES: true
    STAGE_DIR: {{ stage_dir }}

